# Global LLM configuration
[llm]
model = "o1"
api_version = "2025-01-01-preview"
base_url = "https://XXXXX.openai.azure.com/"
api_key = "XXXXXXX"
max_tokens = 4096
temperature = 0.0


# Optional configuration for specific LLM models
[llm.vision]
model = "claude-3-5-sonnet"
base_url = "https://api.openai.com/v1"
api_key = "sk-..."
