# Global LLM configuration
[llm]
model = "o1"
api_version = "2025-01-01-preview"
base_url = "https://openai-hu-east-us2.openai.azure.com/"
api_key = "510d6cd694fa49efab5fb0eccb3e633f"
max_tokens = 4096
temperature = 0.0